# Controller of robot arm joint
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [arm1_joint, arm2_joint, arm3_joint, arm4_joint, arm5_joint]

# Controller to publish the joint_states topic
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50